### ISSUE TITLE
Custom URL support for OAuth redirect

### ISSUE THREAD

**Issue by dev-ritik** [IMGIITRoorkee/omniport-backend#103]
**Is your feature request related to a problem? Please describe.**
The support for custom URL will help in always processing the token through the app and not send a request to the server directly. This was done right in the older channeli OAuth.
The current Omniport OAuth does not allow setting up a redirect URL with a custom schema.

**Describe the solution you'd like**
Update the URLValidator here? https://github.com/IMGIITRoorkee/omniport-backend/blob/f54196585a3561e4c2e399d5293af8f3c5209561/omniport/core/open_auth/serializers/application.py#L137

**Describe alternatives you've considered**
Going with https as schema but that may send the request to the server directly and may not serve the purpose completely.

**Want to take up?**
no

**Comment by pradumangoyal** [comment]
I think we will need to include a custom URL validator which overrides the Django `URLValidator`. In the `__call__` block we may replace the string before `://` to `https` and continue the `URLValidator` call block. @Ajayneethikannan @aru31 @shreyansh23 What do you think of this?

https://stackoverflow.com/questions/49983328/cleanest-way-to-allow-empty-scheme-in-django-urlfield

**Comment by algomaster99** [comment]
@pradumangoyal How about we write our custom Regex for URL Validation?

> we may replace the string before `://` to `https` and continue the `URLValidator` call block

This seems like a _hack_ to me. :sweat_smile:

**Comment by dhruvkb** [comment]
You should not be enforcing the `https` scheme imo. "Some people" could keep their files on an FTP server. Some people also have websites that are still on `http`.

**Comment by rochakjain361** [comment]
I would like to work on this issue.. if possible

**Comment by pradumangoyal** [comment]
Yes, please proceed.

**Comment by dev-ritik** [comment]
@rochakjain361 @algomaster99, can we sort this asap

**Comment by algomaster99** [comment]
@dev-ritik I will try to move this up in our priority list.
