### ISSUE TITLE
First URL for redirection is selected regardless what is sent via `redirect_url`

### ISSUE THREAD

**Issue by algomaster99** [IMGIITRoorkee/omniport-backend#114]
**Describe the bug**
Regardless of what is passed in the query parameter, `redirect_url`, of the URL - `https://internet.channeli.in/oauth/authorise/?client_id=<CLIENT_ID>&redirect_url=<REDIRECT_URL>`, the app always gets redirected to the **first URL** which is registered in the `Application` model.

**To Reproduce**
1. You must have an app which is approved for OAuth.
2. Register multiple `redirect_urls`.
3. Pass any `redirect_url` which is not the first one.

**Expected behavior**
It should redirect to the `URL` which is specified in the `redirect_url` and is also registered in the `redirect_uris` field of Application model.

**Operating System:**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 83.0.4103.116

**Additional Context**
- http://internet.channeli.in/oauth/authorise?client_id=[REDACTED]&redirect_url=http://127.0.0.1:8000/oauth&state=icwueifwueiocujweuilwiebrbilwbeirubeiwruiwerwouiwvuoaweifubi
Even though the `redirect_url` here is http://127.0.0.1:8000/oauth&state=icwueifwueiocujweuilwiebrbilwbeirubeiwruiwerwouiwvuoaweifubi, it will still redirect it to the first URL which is registered.
- This is most likely a bug of `oauth2_provider`

**Want to take up?**
Yes, can mentor any contributor (most probably Project Associates :smile: )

**Comment by pradumangoyal** [comment]
Thanks, @algomaster99 for raising this issue. The issue is prevailing from some time, and it always feels weird as the library itself handles most of this part. 

After this issue it was found that the error is in the documentation part. The query param in which Url is to be passed is mentioned as `redirect_url` but it should be `redirect_uri` according to the current request implementation of the `AuthorisationBox` component in the corresponding service.

So the issue essentially belongs to the repository `omniport-docs` now.

**Comment by pradumangoyal** [comment]
I think it's better to change in the implementation to accept `redirect_url` as the only valid parameter. The reason being the request to obtain the access token also accepts redirect_url parameter in the post request body. Then the issue will belong to repository `omniport-frontend-oauth`.

**Comment by algomaster99** [comment]
You will have to override the `AuthorizationView` imported from `oauth2_provider` to change the implementation so that it finally accepts `redirect_url` as the parameter. I suggest to keep it `redirect_uri` as [RFC](https://tools.ietf.org/html/rfc6749#section-4.1.1) also suggests that and that's why it is implemented like the way it is now in `oauth2_provider`.

**Comment by pradumangoyal** [comment]
I was not referring to change the corresponding backend, but as the RFC suggests, let us go with improving the documentation only.

**Comment by algomaster99** [comment]
@pradumangoyal I tried sending the initial GET request with `redirect_uri`. It seems that it still takes the first URL. 🤔

**Comment by pradumangoyal** [comment]
Actually it is giving an error in getting the access token in @algomaster99 case. One need to change the parameter `redirect_url` to `redirect_uri` in the Post request to get the Access token also.
Essentially, we need to replace all `redirect_url` (case-sensitive) occurrences to the `redirect_uri` on this [page](https://omniport.readthedocs.io/en/latest/how_to/use_oauth2.html#authorising-the-user).
