### ISSUE TITLE
Override and extend Django's startapp command

### ISSUE THREAD

**Issue by dhruvkb** [IMGIITRoorkee/omniport-backend#27]
Override Django's `startapp` management command to add more functionality, a non-exhaustive set of which includes:

- obtain a template from GitHub, created by the person taking this issue up
- create the folder in `apps` or `services` based on the type chosen when invoking the command
- create a decently populated `config.yml` file
- create a URLconf in the Omniport style, i.e. `http_urls.py` and `ws_urls.py`
- create modules for models, views, serializers and consumers rather than files

**Comment by dhruvkb** [comment]
A script for creating new apps was added in commit cf086d3. It still remains to invoke this script when executing Django's `startapp` management command.

**Comment by kmrinal19** [comment]
I would like to work on this issue.

**Comment by pradumangoyal** [comment]
Yes, please proceed. Do check out and try to run the app creation script before working.

**Comment by kmrinal19** [comment]
The directory containing the script for creating new apps is not present inside the docker container.

**Comment by Ajayneethikannan** [comment]
@kmrinal19 mounting it in the start script should do the job I think, since we will be using it only during development anyway

**Comment by kmrinal19** [comment]
Looks like git is not installed inside the container. So, the script to create a new app is unable to clone the app template from github.

**Comment by dhruvkb** [comment]
@kmrinal19 you can [use cURL or wget](https://gist.github.com/jwebcat/5122366). Git is not the only way to clone a repo. Installing Git inside a Python contain would bloat is by a huge amount (especially for a one-time or rare activity).

**Comment by kmrinal19** [comment]
> @kmrinal19 you can [use cURL or wget](https://gist.github.com/jwebcat/5122366). Git is not the only way to clone a repo. Installing Git inside a Python contain would bloat is by a huge amount (especially for a one-time or rare activity).

To use anything other than git I'll have to make changes in the script [app.sh](https://github.com/IMGIITRoorkee/omniport-backend/blob/master/scripts/create/app.sh) or write a new script. @dhruvkb What should I do?

**Comment by dhruvkb** [comment]
See [docs](https://docs.djangoproject.com/en/dev/ref/django-admin/#startapp). Here you can specify the `--template` flag as an `http` link as well so linking to a repo might work very well.

**Comment by kmrinal19** [comment]
I was having 2nd thoughts about this feature. There are some things that [`app.sh`](https://github.com/IMGIITRoorkee/omniport-backend/blob/master/scripts/create/app.sh) can do better like create a git tracked app and also the script runs outside the container, so if we first create an app and then start the container, the app would have already been registered by `discovery` script.

**Comment by algomaster99** [comment]
> create a git tracked app

I believe you can make python do that.

> the app would have already been registered by `discovery` script

Discovery script is executed when the server is started.

**Comment by kmrinal19** [comment]
> I believe you can make python do that.
Git is not installed inside the container.

**Comment by algomaster99** [comment]
@kmrinal19 okay that makes sense. You can try this - https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container
Let us know if it works.

**Comment by kmrinal19** [comment]
> @kmrinal19 okay that makes sense. You can try this - https://stackoverflow.com/questions/32163955/how-to-run-shell-script-on-host-from-docker-container
> Let us know if it works.

There were two solutions which caught my attention. One was to ssh to host from container. The problem here is ssh is not installed inside the container.

The other was to use named pipes. The problem here is that we'll have to run an infinte while loop to listen if startapp command is run.

**Comment by Ajayneethikannan** [comment]
What is the exact step we have in mind, does the user need to enter the container's shell and execute the startapp command, 
or will the old app.sh script be modified to call startapp using a separate container? In the latter, we can just remove the steps involving the template creation inside startapp and leave the git commands as is. 
Other solutions seem to be pretty messy in my opinion.

**Comment by algomaster99** [comment]
That seems like the best solution for it! @kmrinal19

**Comment by Ajayneethikannan** [comment]
Referencing @kmrinal19 's commit here #120

**Comment by algomaster99** [comment]
@Ajayneethikannan can we close this?

**Comment by Ajayneethikannan** [comment]
@algomaster99 Yeah sure 👍
