### ISSUE TITLE
Add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md 

### ISSUE THREAD

**Issue by shreyansh23** [IMGIITRoorkee/omniport-backend#45]
omniport-backend lags behind in terms of github community standards:

![omni-community](https://user-images.githubusercontent.com/32803230/54134142-62a22c80-443d-11e9-99cb-464544ac4995.png)

This can be improved by adding CODE_OF_CONDUCT, CONTRIBUTING, ISSUE_TEMPLATE, and PULL_REQUEST_TEMPLATE to the repository.

**Comment by dhruvkb** [comment]
This is actually a really great idea and should be implemented across all our repositories!
