### ISSUE TITLE
Closing opened file streams

### ISSUE THREAD

**Issue by Ajayneethikannan** [IMGIITRoorkee/omniport-backend#84]
It is a very minor issue but I feel closing these opened file streams would be better.

https://github.com/IMGIITRoorkee/omniport-backend/blob/master/omniport/core/discovery/discovery.py#L80

**Comment by dhruvkb** [comment]
Completely agree. We should use the `with` construct so that it automatically closes streams when done.

**Comment by Ajayneethikannan** [comment]
Will do!
