### ISSUE TITLE
[BUG] 500 error on OAUTH `/open_auth/get_user_data/`

### ISSUE THREAD

**Issue by dev-ritik** [IMGIITRoorkee/omniport-backend#94]
**Describe the bug**
500 error on OAUTH `/open_auth/get_user_data/`

**To Reproduce**
Send a get request without `Authorization` header

**Expected behavior**
401 HTTP Response

**Screenshots**
NA

**Operating System:**
 - OS: [Ubuntu 18.04 LTS]
 - Browser [chrome]
 - Version  79.0.3945.130 (Official Build) (64-bit)

**Additional context**
NA

**Want to take up?**
no

**Comment by pradumangoyal** [comment]
#96
